### ISSUE TITLE
App Mockup shows Link Decoration

### ISSUE THREAD

**Issue by dalliard** [nextsport/nextsport#43]
The App Mockups looks horrible in Firefox. It's about the Link Decoration that every Browser adds differently. Solved this for Chrome with this CSS Entry:

````CSS
a:-webkit-any-link {
  text-decoration: none;
}
````

Will look how I can solve this for every Browser. Looks like this at the Moment:
![2017-03-01-122726_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9986564/23458057/c2e19e74-fe7a-11e6-8af9-cbcb079b41c0.png)
